const data = {
  product: [
    {
      title: 'Erased',
      type: 'tshirt',
      id: '1',
      url: '/shop/pageproduct/1',
      size: 'G',
      image: '/erased-1.jpg',
      price: 54.95,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 20,
    },
    {
      title: 'Erased',
      id: '2',
      type: 'tshirt',
      url: '/shop/pageproduct/2',
      size: 'G',
      image: '/erased-2.jpg',
      price: 60.95,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 15,
    },
    {
      title: 'Erased',
      id: '3',
      type: 'tshirt',
      url: '/shop/pageproduct/3',
      size: 'M',
      image: '/erased-3.jpg',
      price: 67.8,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 12,
    },
    {
      title: 'Orange',
      id: '4',
      type: 'tshirt',
      url: '/shop/pageproduct/4',
      size: 'G',
      image: '/orange-1.jpg',
      price: 150,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 8,
    },
    {
      title: 'Orange',
      id: '5',
      type: 'tshirt',
      url: '/shop/pageproduct/5',
      size: 'P',
      image: '/orange-2.jpg',
      price: 130.99,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 5,
    },
    {
      title: 'Polo Black Purple',
      id: '6',
      type: 'tshirt',
      url: '/shop/pageproduct/6',
      size: 'P',
      image: '/purple-1.jpg',
      price: 130.99,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 5,
    },
    {
      title: 'Erased',
      id: '7',
      type: 'tshirt',
      url: '/shop/pageproduct/7',
      size: 'P',
      image: '/erased-4.webp',
      price: 130.99,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 5,
    },
    {
      title: 'Erased',
      id: '8',
      type: 'tshirt',
      url: '/shop/pageproduct/8',
      size: 'P',
      image: '/erased-5.webp',
      price: 130.99,
      desc: 'A comfortable and stylish t-shirt.',
      stock: 5,
    },
  ],

  users: [
    {
      id: 1,
      email: 'amaral@gmail.com',
      password: '123',
    },
    {
      id: 2,
      email: 'joao@gmail.com',
      password: '345',
    },
  ],
}

export default data
